spring.application.name=TodoAPI
server.port=8080

#spring.datasource.url=jdbc:h2:file:./h2/tododb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
spring.datasource.url=jdbc:h2:tcp://localhost:9092/./tododb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Important: use validate, not create-drop!
spring.jpa.hibernate.ddl-auto=validate


# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false


# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
# Prevents accidental deletion
spring.flyway.clean-disabled=true
# Allows out-of-order migrations
spring.flyway.out-of-order=true


# Flyway setting for H2
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}


# Thymeleaf
spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=true
spring.devtools.livereload.port=35729
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.mvc.hiddenmethod.filter.enabled=true


# Session and cookie settings
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
# Set below to true when using https
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
server.servlet.session.tracking-modes=cookie


# spring-boot-starter-actuator
# http://localhost:8080/actuator/sessions
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info,sessions
management.endpoint.health.show-details=always
management.endpoint.sessions.enabled=true
management.endpoints.web.base-path=/actuator


# Spring Session config
#spring.session.store-type=jdbc
#spring.session.timeout=30m
#spring.session.jdbc.initialize-schema=always
#spring.session.jdbc.table-name=SPRING_SESSION


## Toon SQL statements
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#
## Toon parameter waarden
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.jdbc.core=DEBUG


# Toon security parameters
logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.access=DEBUG
logging.level.org.springframework.security.access.prepost=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web.access.intercept=DEBUG
logging.level.org.springframework.security.web.csrf=DEBUG
