CREATE TABLE IF NOT EXISTS app_user (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email           VARCHAR(255) NOT NULL,
                          name            VARCHAR(200) NOT NULL,
                          password_hash   VARCHAR(255) NOT NULL,
                          created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT uk_app_user_email UNIQUE (email)
);
