CREATE TABLE IF NOT EXISTS list (
                      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      owner_id        BIGINT NOT NULL,
                      name            VARCHAR(200) NOT NULL,
                      description     CLOB,
                      created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_list_owner
                          FOREIGN KEY (owner_id) REFERENCES app_user(id)
                              ON DELETE CASCADE
);

-- Helpful index
CREATE INDEX idx_list_owner_id ON list(owner_id);
