
-- =========================================================
-- Schema: Basic Todo App (Users, Lists, Tasks)
-- DB: H2
-- =========================================================
-- Tested with H2 2.x syntax (compatibility: standard SQL)
-- =========================================================

-- ======================================
-- USERS
-- ======================================
CREATE TABLE app_user (
                          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email           VARCHAR(255) NOT NULL,
                          name            VARCHAR(200) NOT NULL,
                          password_hash   VARCHAR(255) NOT NULL,
                          created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT uk_app_user_email UNIQUE (email)
);

-- ======================================
-- LISTS
-- ======================================
CREATE TABLE list (
                      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      owner_id        BIGINT NOT NULL,
                      name            VARCHAR(200) NOT NULL,
                      description     CLOB,
                      created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_list_owner
                          FOREIGN KEY (owner_id) REFERENCES app_user(id)
                              ON DELETE CASCADE
);

-- Helpful index
CREATE INDEX idx_list_owner_id ON list(owner_id);

-- ======================================
-- TASKS
-- ======================================
CREATE TABLE task (
                      id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      list_id         BIGINT NOT NULL,
                      creator_id      BIGINT NOT NULL,

                      title           VARCHAR(255) NOT NULL,
                      description     CLOB,

                      status          VARCHAR(20) NOT NULL,
                      due_date        DATE,
                      priority        INT,
                      created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      completed_at    TIMESTAMP,

                      CONSTRAINT fk_task_list
                          FOREIGN KEY (list_id) REFERENCES list(id)
                              ON DELETE CASCADE,

                      CONSTRAINT fk_task_creator
                          FOREIGN KEY (creator_id) REFERENCES app_user(id)
                              ON DELETE RESTRICT,

    -- Enum-like checks (H2 doesn't have native ENUM)
                      CONSTRAINT chk_task_status
                          CHECK (status IN ('todo', 'in_progress', 'done', 'archived')),

                      CONSTRAINT chk_task_priority
                          CHECK (priority IS NULL OR (priority BETWEEN 1 AND 5))
);

-- Helpful indexes
CREATE INDEX idx_task_list_id       ON task(list_id);
CREATE INDEX idx_task_status        ON task(status);
CREATE INDEX idx_task_due_date      ON task(due_date);
CREATE INDEX idx_task_completed_at  ON task(completed_at);

-- Optional composite index for list work queues
CREATE INDEX idx_task_list_status_due ON task(list_id, status, due_date);
